//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
	public static class HelperFunctions
	{
		/// <summary>
		/// Determines if this collider is solid and non-static.
		/// </summary>
		public static bool CanReceiveForces(Collider input)
		{
			return input.attachedRigidbody != null && !input.attachedRigidbody.isKinematic && !input.isTrigger;
		}
	}
}

